# Base16 Vice Dark - amfora color config
# Thomas Leon Highbaugh

[theme]
bg = "#181818"
fg = "#818181"

bottombar_label = "#00f6d9"
bottombar_text = "#818181"
bottombar_bg = "#222222"

tab_num = "#323232"
tab_divider = "#666666"

amfora_link = "#0badff"
foreign_link = "#3f3f3f"
link_number = "#3f3f3f"

btn_bg = "#222222"
btn_text = "#818181"

input_modal_bg = "#222222"
input_modal_text = "#818181"
input_modal_field_bg = "#181818"
input_modal_field_text = "#818181"
info_modal_bg = "#222222"
info_modal_text = "#818181"
error_modal_bg = "#222222"
error_modal_text = "#ff3d81"
yesno_modal_bg = "#222222"
yesno_modal_text = "#818181"
tofu_modal_bg = "#222222"
tofu_modal_text = "#818181"
subscription_modal_bg = "#222222"
subscription_modal_text = "#818181"

hdg_1 = "#85ffe0"
hdg_2 = "#f0ffaa"
hdg_3 = "#00eaff"
regular_text = "#818181"
preformatted_text = "#8265ff"
list_text = "#818181"
