# Base16 Vice Alt - amfora color config
# Thomas Leon Highbaugh

[theme]
bg = "#303030"
fg = "#d7afff"

bottombar_label = "#d7afff"
bottombar_text = "#d7afff"
bottombar_bg = "#444444"

tab_num = "#878787"
tab_divider = "#afafd7"

amfora_link = "#87ffff"
foreign_link = "#875faf"
link_number = "#875faf"

btn_bg = "#444444"
btn_text = "#d7afff"

input_modal_bg = "#444444"
input_modal_text = "#d7afff"
input_modal_field_bg = "#303030"
input_modal_field_text = "#d7afff"
info_modal_bg = "#444444"
info_modal_text = "#d7afff"
error_modal_bg = "#444444"
error_modal_text = "#ff87d7"
yesno_modal_bg = "#444444"
yesno_modal_text = "#d7afff"
tofu_modal_bg = "#444444"
tofu_modal_text = "#d7afff"
subscription_modal_bg = "#444444"
subscription_modal_text = "#d7afff"

hdg_1 = "#ff00ff"
hdg_2 = "#ffffaf"
hdg_3 = "#afffff"
regular_text = "#d7afff"
preformatted_text = "#00ffaf"
list_text = "#d7afff"
