# Base16 Humanoid dark - wezterm color config
# Scheme by Thomas (tasmo) Friese

[colors]
foreground    = "#f8f8f2"
background    = "#232629"
cursor_bg     = "#f8f8f2"
cursor_border = "#f8f8f2"
cursor_fg     = "#232629"
selection_bg  = "#f8f8f2"
selection_fg  = "#232629"

ansi = [
  "#232629",
  "#f11235",
  "#02d849",
  "#ffb627",
  "#00a6fb",
  "#f15ee3",
  "#0dd9d6",
  "#f8f8f2"
]

brights = [
  "#60615d",
  "#f11235",
  "#02d849",
  "#ffb627",
  "#00a6fb",
  "#f15ee3",
  "#0dd9d6",
  "#fcfcfc"
]
