# Base16 Ros√© Pine Moon - wezterm color config
# Scheme by Emilia Dunfelt &lt;edun@dunfelt.se&gt;

[colors]
foreground    = "#e0def4"
background    = "#232136"
cursor_bg     = "#e0def4"
cursor_border = "#e0def4"
cursor_fg     = "#232136"
selection_bg  = "#e0def4"
selection_fg  = "#232136"

ansi = [
  "#232136",
  "#eb6f92",
  "#3e8fb0",
  "#ea9a97",
  "#c4a7e7",
  "#f6c177",
  "#9ccfd8",
  "#e0def4"
]

brights = [
  "#6e6a86",
  "#eb6f92",
  "#3e8fb0",
  "#ea9a97",
  "#c4a7e7",
  "#f6c177",
  "#9ccfd8",
  "#56526e"
]
