# Base16 Vice Dark - wezterm color config
# Scheme by Thomas Leon Highbaugh

[colors]
foreground    = "#818181"
background    = "#181818"
cursor_bg     = "#818181"
cursor_border = "#818181"
cursor_fg     = "#181818"
selection_bg  = "#818181"
selection_fg  = "#181818"

ansi = [
  "#181818",
  "#ff29a8",
  "#0badff",
  "#f0ffaa",
  "#00eaff",
  "#00f6d9",
  "#8265ff",
  "#818181"
]

brights = [
  "#3f3f3f",
  "#ff29a8",
  "#0badff",
  "#f0ffaa",
  "#00eaff",
  "#00f6d9",
  "#8265ff",
  "#e9e9e9"
]
