# Base16 Windows 95 - wezterm color config
# Scheme by Fergus Collins (https://github.com/C-Fergus)

[colors]
foreground    = "#a8a8a8"
background    = "#000000"
cursor_bg     = "#a8a8a8"
cursor_border = "#a8a8a8"
cursor_fg     = "#000000"
selection_bg  = "#a8a8a8"
selection_fg  = "#000000"

ansi = [
  "#000000",
  "#fc5454",
  "#54fc54",
  "#fcfc54",
  "#5454fc",
  "#fc54fc",
  "#54fcfc",
  "#a8a8a8"
]

brights = [
  "#545454",
  "#fc5454",
  "#54fc54",
  "#fcfc54",
  "#5454fc",
  "#fc54fc",
  "#54fcfc",
  "#fcfcfc"
]
