# Base16 Monokai - wezterm color config
# Scheme by Wimer Hazenberg (http://www.monokai.nl)

[colors]
foreground    = "#f8f8f2"
background    = "#272822"
cursor_bg     = "#f8f8f2"
cursor_border = "#f8f8f2"
cursor_fg     = "#272822"
selection_bg  = "#f8f8f2"
selection_fg  = "#272822"

ansi = [
  "#272822",
  "#f92672",
  "#a6e22e",
  "#f4bf75",
  "#66d9ef",
  "#ae81ff",
  "#a1efe4",
  "#f8f8f2"
]

brights = [
  "#75715e",
  "#f92672",
  "#a6e22e",
  "#f4bf75",
  "#66d9ef",
  "#ae81ff",
  "#a1efe4",
  "#f9f8f5"
]
