# Base16 Grayscale Dark - wezterm color config
# Scheme by Alexandre Gavioli (https://github.com/Alexx2/)

[colors]
foreground    = "#b9b9b9"
background    = "#101010"
cursor_bg     = "#b9b9b9"
cursor_border = "#b9b9b9"
cursor_fg     = "#101010"
selection_bg  = "#b9b9b9"
selection_fg  = "#101010"

ansi = [
  "#101010",
  "#7c7c7c",
  "#8e8e8e",
  "#a0a0a0",
  "#686868",
  "#747474",
  "#868686",
  "#b9b9b9"
]

brights = [
  "#525252",
  "#7c7c7c",
  "#8e8e8e",
  "#a0a0a0",
  "#686868",
  "#747474",
  "#868686",
  "#f7f7f7"
]
