# Base16 Summerfruit Dark - wezterm color config
# Scheme by Christopher Corley (http://christop.club/)

[colors]
foreground    = "#D0D0D0"
background    = "#151515"
cursor_bg     = "#D0D0D0"
cursor_border = "#D0D0D0"
cursor_fg     = "#151515"
selection_bg  = "#D0D0D0"
selection_fg  = "#151515"

ansi = [
  "#151515",
  "#FF0086",
  "#00C918",
  "#ABA800",
  "#3777E6",
  "#AD00A1",
  "#1FAAAA",
  "#D0D0D0"
]

brights = [
  "#505050",
  "#FF0086",
  "#00C918",
  "#ABA800",
  "#3777E6",
  "#AD00A1",
  "#1FAAAA",
  "#FFFFFF"
]
