# Base16 Ros√© Pine Dawn - wezterm color config
# Scheme by Emilia Dunfelt &lt;edun@dunfelt.se&gt;

[colors]
foreground    = "#575279"
background    = "#faf4ed"
cursor_bg     = "#575279"
cursor_border = "#575279"
cursor_fg     = "#faf4ed"
selection_bg  = "#575279"
selection_fg  = "#faf4ed"

ansi = [
  "#faf4ed",
  "#b4637a",
  "#286983",
  "#d7827e",
  "#907aa9",
  "#ea9d34",
  "#56949f",
  "#575279"
]

brights = [
  "#9893a5",
  "#b4637a",
  "#286983",
  "#d7827e",
  "#907aa9",
  "#ea9d34",
  "#56949f",
  "#cecacd"
]
