# Base16 Brush Trees - wezterm color config
# Scheme by Abraham White &lt;abelincoln.white@gmail.com&gt;

[colors]
foreground    = "#6D828E"
background    = "#E3EFEF"
cursor_bg     = "#6D828E"
cursor_border = "#6D828E"
cursor_fg     = "#E3EFEF"
selection_bg  = "#6D828E"
selection_fg  = "#E3EFEF"

ansi = [
  "#E3EFEF",
  "#b38686",
  "#87b386",
  "#aab386",
  "#868cb3",
  "#b386b2",
  "#86b3b3",
  "#6D828E"
]

brights = [
  "#98AFB5",
  "#b38686",
  "#87b386",
  "#aab386",
  "#868cb3",
  "#b386b2",
  "#86b3b3",
  "#485867"
]
