# Base16 PaperColor Dark - wezterm color config
# Scheme by Jon Leopard (http://github.com/jonleopard) based on PaperColor Theme (https://github.com/NLKNguyen/papercolor-theme)

[colors]
foreground    = "#808080"
background    = "#1c1c1c"
cursor_bg     = "#808080"
cursor_border = "#808080"
cursor_fg     = "#1c1c1c"
selection_bg  = "#808080"
selection_fg  = "#1c1c1c"

ansi = [
  "#1c1c1c",
  "#585858",
  "#af87d7",
  "#afd700",
  "#ff5faf",
  "#00afaf",
  "#ffaf00",
  "#808080"
]

brights = [
  "#d7af5f",
  "#585858",
  "#af87d7",
  "#afd700",
  "#ff5faf",
  "#00afaf",
  "#ffaf00",
  "#d0d0d0"
]
