# Base16 Flat - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground    = "#e0e0e0"
background    = "#2C3E50"
cursor_bg     = "#e0e0e0"
cursor_border = "#e0e0e0"
cursor_fg     = "#2C3E50"
selection_bg  = "#e0e0e0"
selection_fg  = "#2C3E50"

ansi = [
  "#2C3E50",
  "#E74C3C",
  "#2ECC71",
  "#F1C40F",
  "#3498DB",
  "#9B59B6",
  "#1ABC9C",
  "#e0e0e0"
]

brights = [
  "#95A5A6",
  "#E74C3C",
  "#2ECC71",
  "#F1C40F",
  "#3498DB",
  "#9B59B6",
  "#1ABC9C",
  "#ECF0F1"
]
