# Base16 Atelier Sulphurpool Light - wezterm color config
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)

[colors]
foreground    = "#5e6687"
background    = "#f5f7ff"
cursor_bg     = "#5e6687"
cursor_border = "#5e6687"
cursor_fg     = "#f5f7ff"
selection_bg  = "#5e6687"
selection_fg  = "#f5f7ff"

ansi = [
  "#f5f7ff",
  "#c94922",
  "#ac9739",
  "#c08b30",
  "#3d8fd1",
  "#6679cc",
  "#22a2c9",
  "#5e6687"
]

brights = [
  "#898ea4",
  "#c94922",
  "#ac9739",
  "#c08b30",
  "#3d8fd1",
  "#6679cc",
  "#22a2c9",
  "#202746"
]
