# Base16 Sakura - wezterm color config
# Scheme by Misterio77 (http://github.com/Misterio77)

[colors]
foreground    = "#564448"
background    = "#feedf3"
cursor_bg     = "#564448"
cursor_border = "#564448"
cursor_fg     = "#feedf3"
selection_bg  = "#564448"
selection_fg  = "#feedf3"

ansi = [
  "#feedf3",
  "#df2d52",
  "#2e916d",
  "#c29461",
  "#006e93",
  "#5e2180",
  "#1d8991",
  "#564448"
]

brights = [
  "#755f64",
  "#df2d52",
  "#2e916d",
  "#c29461",
  "#006e93",
  "#5e2180",
  "#1d8991",
  "#33292b"
]
