# Base16 tender - wezterm color config
# Scheme by Jacobo Tabernero (https://github/com/jacoborus/tender.vim)

[colors]
foreground    = "#eeeeee"
background    = "#282828"
cursor_bg     = "#eeeeee"
cursor_border = "#eeeeee"
cursor_fg     = "#282828"
selection_bg  = "#eeeeee"
selection_fg  = "#282828"

ansi = [
  "#282828",
  "#f43753",
  "#c9d05c",
  "#ffc24b",
  "#b3deef",
  "#d3b987",
  "#73cef4",
  "#eeeeee"
]

brights = [
  "#4c4c4c",
  "#f43753",
  "#c9d05c",
  "#ffc24b",
  "#b3deef",
  "#d3b987",
  "#73cef4",
  "#feffff"
]
