# Base16 Summerfruit Light - wezterm color config
# Scheme by Christopher Corley (http://christop.club/)

[colors]
foreground    = "#101010"
background    = "#FFFFFF"
cursor_bg     = "#101010"
cursor_border = "#101010"
cursor_fg     = "#FFFFFF"
selection_bg  = "#101010"
selection_fg  = "#FFFFFF"

ansi = [
  "#FFFFFF",
  "#FF0086",
  "#00C918",
  "#ABA800",
  "#3777E6",
  "#AD00A1",
  "#1FAAAA",
  "#101010"
]

brights = [
  "#B0B0B0",
  "#FF0086",
  "#00C918",
  "#ABA800",
  "#3777E6",
  "#AD00A1",
  "#1FAAAA",
  "#202020"
]
