# Base16 Windows NT - wezterm color config
# Scheme by Fergus Collins (https://github.com/C-Fergus)

[colors]
foreground    = "#c0c0c0"
background    = "#000000"
cursor_bg     = "#c0c0c0"
cursor_border = "#c0c0c0"
cursor_fg     = "#000000"
selection_bg  = "#c0c0c0"
selection_fg  = "#000000"

ansi = [
  "#000000",
  "#ff0000",
  "#00ff00",
  "#ffff00",
  "#0000ff",
  "#ff00ff",
  "#00ffff",
  "#c0c0c0"
]

brights = [
  "#808080",
  "#ff0000",
  "#00ff00",
  "#ffff00",
  "#0000ff",
  "#ff00ff",
  "#00ffff",
  "#ffffff"
]
