# Base16 Atlas - wezterm color config
# Scheme by Alex Lende (https://ajlende.com)

[colors]
foreground    = "#a1a19a"
background    = "#002635"
cursor_bg     = "#a1a19a"
cursor_border = "#a1a19a"
cursor_fg     = "#002635"
selection_bg  = "#a1a19a"
selection_fg  = "#002635"

ansi = [
  "#002635",
  "#ff5a67",
  "#7fc06e",
  "#ffcc1b",
  "#14747e",
  "#9a70a4",
  "#5dd7b9",
  "#a1a19a"
]

brights = [
  "#6C8B91",
  "#ff5a67",
  "#7fc06e",
  "#ffcc1b",
  "#14747e",
  "#9a70a4",
  "#5dd7b9",
  "#fafaf8"
]
