# Base16 Windows High Contrast Light - wezterm color config
# Scheme by Fergus Collins (https://github.com/C-Fergus)

[colors]
foreground    = "#545454"
background    = "#fcfcfc"
cursor_bg     = "#545454"
cursor_border = "#545454"
cursor_fg     = "#fcfcfc"
selection_bg  = "#545454"
selection_fg  = "#fcfcfc"

ansi = [
  "#fcfcfc",
  "#800000",
  "#008000",
  "#808000",
  "#000080",
  "#800080",
  "#008080",
  "#545454"
]

brights = [
  "#c0c0c0",
  "#800000",
  "#008000",
  "#808000",
  "#000080",
  "#800080",
  "#008080",
  "#000000"
]
