# Base16 Vice Alt - wezterm color config
# Scheme by Thomas Leon Highbaugh

[colors]
foreground    = "#d7afff"
background    = "#303030"
cursor_bg     = "#d7afff"
cursor_border = "#d7afff"
cursor_fg     = "#303030"
selection_bg  = "#d7afff"
selection_fg  = "#303030"

ansi = [
  "#303030",
  "#ff005f",
  "#87ffff",
  "#ffffaf",
  "#afffff",
  "#d7afff",
  "#00ffaf",
  "#d7afff"
]

brights = [
  "#875faf",
  "#ff005f",
  "#87ffff",
  "#ffffaf",
  "#afffff",
  "#d7afff",
  "#00ffaf",
  "#afffd7"
]
