# Base16 London Tube - wezterm color config
# Scheme by Jan T. Sott

[colors]
foreground    = "#d9d8d8"
background    = "#231f20"
cursor_bg     = "#d9d8d8"
cursor_border = "#d9d8d8"
cursor_fg     = "#231f20"
selection_bg  = "#d9d8d8"
selection_fg  = "#231f20"

ansi = [
  "#231f20",
  "#ee2e24",
  "#00853e",
  "#ffd204",
  "#009ddc",
  "#98005d",
  "#85cebc",
  "#d9d8d8"
]

brights = [
  "#737171",
  "#ee2e24",
  "#00853e",
  "#ffd204",
  "#009ddc",
  "#98005d",
  "#85cebc",
  "#ffffff"
]
