# Base16 Mocha - wezterm color config
# Scheme by Chris Kempson (http://chriskempson.com)

[colors]
foreground    = "#d0c8c6"
background    = "#3B3228"
cursor_bg     = "#d0c8c6"
cursor_border = "#d0c8c6"
cursor_fg     = "#3B3228"
selection_bg  = "#d0c8c6"
selection_fg  = "#3B3228"

ansi = [
  "#3B3228",
  "#cb6077",
  "#beb55b",
  "#f4bc87",
  "#8ab3b5",
  "#a89bb9",
  "#7bbda4",
  "#d0c8c6"
]

brights = [
  "#7e705a",
  "#cb6077",
  "#beb55b",
  "#f4bc87",
  "#8ab3b5",
  "#a89bb9",
  "#7bbda4",
  "#f5eeeb"
]
