# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Vice Alt by Thomas Leon Highbaugh

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#303030"
idle_fg = "#d7afff"
info_bg = "#00ffaf"
info_fg = "#303030"
good_bg = "#87ffff"
good_fg = "#303030"
warning_bg = "#ffffaf"
warning_fg = "#303030"
critical_bg = "#ff005f"
critical_fg = "#303030"
# The rest of the theme settings are left at default.
