# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Vice Dark by Thomas Leon Highbaugh

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#181818"
idle_fg = "#818181"
info_bg = "#8265ff"
info_fg = "#181818"
good_bg = "#0badff"
good_fg = "#181818"
warning_bg = "#f0ffaa"
warning_fg = "#181818"
critical_bg = "#ff29a8"
critical_fg = "#181818"
# The rest of the theme settings are left at default.
