# Base16 XCode Dusk 256 - alacritty color config
# Elsa Gonsiorowski (https://github.com/gonsie)

# Default colors
[colors.primary]
background = '0x282B35'
foreground = '0x939599'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x282B35'
cursor = '0x939599'

# Normal colors
[colors.normal]
black = '0x282B35'
red = '0xB21889'
green = '0xDF0002'
yellow = '0x438288'
blue = '0x790EAD'
magenta = '0xB21889'
cyan = '0x00A0BE'
white = '0x939599'

# Bright colors
[colors.bright]
black = '0x686A71'
red = '0xB21889'
green = '0xDF0002'
yellow = '0x438288'
blue = '0x790EAD'
magenta = '0xB21889'
cyan = '0x00A0BE'
white = '0xBEBFC2'

[[colors.indexed_colors]]
index = 16
color = "0x786DC5"

[[colors.indexed_colors]]
index = 17
color = "0xC77C48"

[[colors.indexed_colors]]
index = 18
color = "0x3D4048"

[[colors.indexed_colors]]
index = 19
color = "0x53555D"

[[colors.indexed_colors]]
index = 20
color = "0x7E8086"

[[colors.indexed_colors]]
index = 21
color = "0xA9AAAE"
