# Base16 Vice Alt 256 - alacritty color config
# Thomas Leon Highbaugh

# Default colors
[colors.primary]
background = '0x303030'
foreground = '0xd7afff'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x303030'
cursor = '0xd7afff'

# Normal colors
[colors.normal]
black = '0x303030'
red = '0xff005f'
green = '0x87ffff'
yellow = '0xffffaf'
blue = '0xafffff'
magenta = '0xd7afff'
cyan = '0x00ffaf'
white = '0xd7afff'

# Bright colors
[colors.bright]
black = '0x875faf'
red = '0xff005f'
green = '0x87ffff'
yellow = '0xffffaf'
blue = '0xafffff'
magenta = '0xd7afff'
cyan = '0x00ffaf'
white = '0xafffd7'

[[colors.indexed_colors]]
index = 16
color = "0xff00ff"

[[colors.indexed_colors]]
index = 17
color = "0xff87d7"

[[colors.indexed_colors]]
index = 18
color = "0x444444"

[[colors.indexed_colors]]
index = 19
color = "0x878787"

[[colors.indexed_colors]]
index = 20
color = "0xafafd7"

[[colors.indexed_colors]]
index = 21
color = "0xffffff"
