# Base16 Solar Flare Light 256 - alacritty color config
# Chuck Harmston (https://chuck.harmston.ch)

# Default colors
[colors.primary]
background = '0xF5F7FA'
foreground = '0x586875'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xF5F7FA'
cursor = '0x586875'

# Normal colors
[colors.normal]
black = '0xF5F7FA'
red = '0xEF5253'
green = '0x7CC844'
yellow = '0xE4B51C'
blue = '0x33B5E1'
magenta = '0xA363D5'
cyan = '0x52CBB0'
white = '0x586875'

# Bright colors
[colors.bright]
black = '0x85939E'
red = '0xEF5253'
green = '0x7CC844'
yellow = '0xE4B51C'
blue = '0x33B5E1'
magenta = '0xA363D5'
cyan = '0x52CBB0'
white = '0x18262F'

[[colors.indexed_colors]]
index = 16
color = "0xE66B2B"

[[colors.indexed_colors]]
index = 17
color = "0xD73C9A"

[[colors.indexed_colors]]
index = 18
color = "0xE8E9ED"

[[colors.indexed_colors]]
index = 19
color = "0xA6AFB8"

[[colors.indexed_colors]]
index = 20
color = "0x667581"

[[colors.indexed_colors]]
index = 21
color = "0x222E38"
