# Base16 DanQing Light 256 - alacritty color config
# Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)

# Default colors
[colors.primary]
background = '0xfcfefd'
foreground = '0x5a605d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfcfefd'
cursor = '0x5a605d'

# Normal colors
[colors.normal]
black = '0xfcfefd'
red = '0xF9906F'
green = '0x8AB361'
yellow = '0xF0C239'
blue = '0xB0A4E3'
magenta = '0xCCA4E3'
cyan = '0x30DFF3'
white = '0x5a605d'

# Bright colors
[colors.bright]
black = '0xcad8d2'
red = '0xF9906F'
green = '0x8AB361'
yellow = '0xF0C239'
blue = '0xB0A4E3'
magenta = '0xCCA4E3'
cyan = '0x30DFF3'
white = '0x2d302f'

[[colors.indexed_colors]]
index = 16
color = "0xB38A61"

[[colors.indexed_colors]]
index = 17
color = "0xCA6924"

[[colors.indexed_colors]]
index = 18
color = "0xecf6f2"

[[colors.indexed_colors]]
index = 19
color = "0xe0f0eF"

[[colors.indexed_colors]]
index = 20
color = "0x9da8a3"

[[colors.indexed_colors]]
index = 21
color = "0x434846"
