# Base16 Horizon Dark 256 - alacritty color config
# MichaÃ«l Ball (http://github.com/michael-ball/)

# Default colors
[colors.primary]
background = '0x1C1E26'
foreground = '0xCBCED0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1C1E26'
cursor = '0xCBCED0'

# Normal colors
[colors.normal]
black = '0x1C1E26'
red = '0xE93C58'
green = '0xEFAF8E'
yellow = '0xEFB993'
blue = '0xDF5273'
magenta = '0xB072D1'
cyan = '0x24A8B4'
white = '0xCBCED0'

# Bright colors
[colors.bright]
black = '0x6F6F70'
red = '0xE93C58'
green = '0xEFAF8E'
yellow = '0xEFB993'
blue = '0xDF5273'
magenta = '0xB072D1'
cyan = '0x24A8B4'
white = '0xE3E6EE'

[[colors.indexed_colors]]
index = 16
color = "0xE58D7D"

[[colors.indexed_colors]]
index = 17
color = "0xE4A382"

[[colors.indexed_colors]]
index = 18
color = "0x232530"

[[colors.indexed_colors]]
index = 19
color = "0x2E303E"

[[colors.indexed_colors]]
index = 20
color = "0x9DA0A2"

[[colors.indexed_colors]]
index = 21
color = "0xDCDFE4"
