# Base16 Google Light 256 - alacritty color config
# Seth Wright (http://sethawright.com)

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x373b41'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x373b41'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xCC342B'
green = '0x198844'
yellow = '0xFBA922'
blue = '0x3971ED'
magenta = '0xA36AC7'
cyan = '0x3971ED'
white = '0x373b41'

# Bright colors
[colors.bright]
black = '0xb4b7b4'
red = '0xCC342B'
green = '0x198844'
yellow = '0xFBA922'
blue = '0x3971ED'
magenta = '0xA36AC7'
cyan = '0x3971ED'
white = '0x1d1f21'

[[colors.indexed_colors]]
index = 16
color = "0xF96A38"

[[colors.indexed_colors]]
index = 17
color = "0x3971ED"

[[colors.indexed_colors]]
index = 18
color = "0xe0e0e0"

[[colors.indexed_colors]]
index = 19
color = "0xc5c8c6"

[[colors.indexed_colors]]
index = 20
color = "0x969896"

[[colors.indexed_colors]]
index = 21
color = "0x282a2e"
