# Base16 Summerfruit Dark 256 - alacritty color config
# Christopher Corley (http://christop.club/)

# Default colors
[colors.primary]
background = '0x151515'
foreground = '0xD0D0D0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x151515'
cursor = '0xD0D0D0'

# Normal colors
[colors.normal]
black = '0x151515'
red = '0xFF0086'
green = '0x00C918'
yellow = '0xABA800'
blue = '0x3777E6'
magenta = '0xAD00A1'
cyan = '0x1FAAAA'
white = '0xD0D0D0'

# Bright colors
[colors.bright]
black = '0x505050'
red = '0xFF0086'
green = '0x00C918'
yellow = '0xABA800'
blue = '0x3777E6'
magenta = '0xAD00A1'
cyan = '0x1FAAAA'
white = '0xFFFFFF'

[[colors.indexed_colors]]
index = 16
color = "0xFD8900"

[[colors.indexed_colors]]
index = 17
color = "0xCC6633"

[[colors.indexed_colors]]
index = 18
color = "0x202020"

[[colors.indexed_colors]]
index = 19
color = "0x303030"

[[colors.indexed_colors]]
index = 20
color = "0xB0B0B0"

[[colors.indexed_colors]]
index = 21
color = "0xE0E0E0"
