# Base16 Embers 256 - alacritty color config
# Jannik Siebert (https://github.com/janniks)

# Default colors
[colors.primary]
background = '0x16130F'
foreground = '0xA39A90'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x16130F'
cursor = '0xA39A90'

# Normal colors
[colors.normal]
black = '0x16130F'
red = '0x826D57'
green = '0x57826D'
yellow = '0x6D8257'
blue = '0x6D5782'
magenta = '0x82576D'
cyan = '0x576D82'
white = '0xA39A90'

# Bright colors
[colors.bright]
black = '0x5A5047'
red = '0x826D57'
green = '0x57826D'
yellow = '0x6D8257'
blue = '0x6D5782'
magenta = '0x82576D'
cyan = '0x576D82'
white = '0xDBD6D1'

[[colors.indexed_colors]]
index = 16
color = "0x828257"

[[colors.indexed_colors]]
index = 17
color = "0x825757"

[[colors.indexed_colors]]
index = 18
color = "0x2C2620"

[[colors.indexed_colors]]
index = 19
color = "0x433B32"

[[colors.indexed_colors]]
index = 20
color = "0x8A8075"

[[colors.indexed_colors]]
index = 21
color = "0xBEB6AE"
