# Base16 Outrun Dark 256 - alacritty color config
# Hugo Delahousse (http://github.com/hugodelahousse/)

# Default colors
[colors.primary]
background = '0x00002A'
foreground = '0xD0D0FA'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x00002A'
cursor = '0xD0D0FA'

# Normal colors
[colors.normal]
black = '0x00002A'
red = '0xFF4242'
green = '0x59F176'
yellow = '0xF3E877'
blue = '0x66B0FF'
magenta = '0xF10596'
cyan = '0x0EF0F0'
white = '0xD0D0FA'

# Bright colors
[colors.bright]
black = '0x50507A'
red = '0xFF4242'
green = '0x59F176'
yellow = '0xF3E877'
blue = '0x66B0FF'
magenta = '0xF10596'
cyan = '0x0EF0F0'
white = '0xF5F5FF'

[[colors.indexed_colors]]
index = 16
color = "0xFC8D28"

[[colors.indexed_colors]]
index = 17
color = "0xF003EF"

[[colors.indexed_colors]]
index = 18
color = "0x20204A"

[[colors.indexed_colors]]
index = 19
color = "0x30305A"

[[colors.indexed_colors]]
index = 20
color = "0xB0B0DA"

[[colors.indexed_colors]]
index = 21
color = "0xE0E0FF"
