# Base16 srcery - alacritty color config
# 

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1C1B19'
foreground = '0xBAA67F'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1C1B19'
cursor = '0xBAA67F'

# Normal colors
[colors.normal]
black = '0x1C1B19'
red = '0xEF2F27'
green = '0x519F50'
yellow = '0xFBB829'
blue = '0x2C78BF'
magenta = '0xE02C6D'
cyan = '0x0AAEB3'
white = '0xBAA67F'

# Bright colors
[colors.bright]
black = '0x918175'
red = '0xFF5F00'
green = '0x98BC37'
yellow = '0xFED06E'
blue = '0x68A8E4'
magenta = '0xFF5C8F'
cyan = '0x2BE4D0'
white = '0xFCE8C3'
