# Base16 Materia 256 - alacritty color config
# Defman21

# Default colors
[colors.primary]
background = '0x263238'
foreground = '0xCDD3DE'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x263238'
cursor = '0xCDD3DE'

# Normal colors
[colors.normal]
black = '0x263238'
red = '0xEC5F67'
green = '0x8BD649'
yellow = '0xFFCC00'
blue = '0x89DDFF'
magenta = '0x82AAFF'
cyan = '0x80CBC4'
white = '0xCDD3DE'

# Bright colors
[colors.bright]
black = '0x707880'
red = '0xEC5F67'
green = '0x8BD649'
yellow = '0xFFCC00'
blue = '0x89DDFF'
magenta = '0x82AAFF'
cyan = '0x80CBC4'
white = '0xFFFFFF'

[[colors.indexed_colors]]
index = 16
color = "0xEA9560"

[[colors.indexed_colors]]
index = 17
color = "0xEC5F67"

[[colors.indexed_colors]]
index = 18
color = "0x2C393F"

[[colors.indexed_colors]]
index = 19
color = "0x37474F"

[[colors.indexed_colors]]
index = 20
color = "0xC9CCD3"

[[colors.indexed_colors]]
index = 21
color = "0xD5DBE5"
