# Base16 srcery 256 - alacritty color config
# 

# Default colors
[colors.primary]
background = '0x1C1B19'
foreground = '0xBAA67F'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1C1B19'
cursor = '0xBAA67F'

# Normal colors
[colors.normal]
black = '0x1C1B19'
red = '0xEF2F27'
green = '0x519F50'
yellow = '0xFBB829'
blue = '0x2C78BF'
magenta = '0xE02C6D'
cyan = '0x0AAEB3'
white = '0xBAA67F'

# Bright colors
[colors.bright]
black = '0x918175'
red = '0xEF2F27'
green = '0x519F50'
yellow = '0xFBB829'
blue = '0x2C78BF'
magenta = '0xE02C6D'
cyan = '0x0AAEB3'
white = '0xFCE8C3'

[[colors.indexed_colors]]
index = 16
color = "0xFF5F00"

[[colors.indexed_colors]]
index = 17
color = "0x2BE4D0"

[[colors.indexed_colors]]
index = 18
color = "0x98BC37"

[[colors.indexed_colors]]
index = 19
color = "0xFED06E"

[[colors.indexed_colors]]
index = 20
color = "0x68A8E4"

[[colors.indexed_colors]]
index = 21
color = "0xFF5C8F"
