# Base16 Pasque 256 - alacritty color config
# Gabriel Fontes (https://github.com/Misterio77)

# Default colors
[colors.primary]
background = '0x271C3A'
foreground = '0xDEDCDF'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x271C3A'
cursor = '0xDEDCDF'

# Normal colors
[colors.normal]
black = '0x271C3A'
red = '0xA92258'
green = '0xC6914B'
yellow = '0x804ead'
blue = '0x8E7DC6'
magenta = '0x953B9D'
cyan = '0x7263AA'
white = '0xDEDCDF'

# Bright colors
[colors.bright]
black = '0x5D5766'
red = '0xA92258'
green = '0xC6914B'
yellow = '0x804ead'
blue = '0x8E7DC6'
magenta = '0x953B9D'
cyan = '0x7263AA'
white = '0xBBAADD'

[[colors.indexed_colors]]
index = 16
color = "0x918889"

[[colors.indexed_colors]]
index = 17
color = "0x59325C"

[[colors.indexed_colors]]
index = 18
color = "0x100323"

[[colors.indexed_colors]]
index = 19
color = "0x3E2D5C"

[[colors.indexed_colors]]
index = 20
color = "0xBEBCBF"

[[colors.indexed_colors]]
index = 21
color = "0xEDEAEF"
