# Base16 Rigel 256 - alacritty color config
# Alexander Keliris

# Default colors
[colors.primary]
background = '0x00384d'
foreground = '0x77929e'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x00384d'
cursor = '0x77929e'

# Normal colors
[colors.normal]
black = '0x00384d'
red = '0xc43061'
green = '0x7fc06e'
yellow = '0xf08e48'
blue = '0x1c8db2'
magenta = '0xc694ff'
cyan = '0x00cccc'
white = '0x77929e'

# Bright colors
[colors.bright]
black = '0x517f8d'
red = '0xc43061'
green = '0x7fc06e'
yellow = '0xf08e48'
blue = '0x1c8db2'
magenta = '0xc694ff'
cyan = '0x00cccc'
white = '0xe6e6dc'

[[colors.indexed_colors]]
index = 16
color = "0xff5a67"

[[colors.indexed_colors]]
index = 17
color = "0x00ffff"

[[colors.indexed_colors]]
index = 18
color = "0x9cf087"

[[colors.indexed_colors]]
index = 19
color = "0xffcc1b"

[[colors.indexed_colors]]
index = 20
color = "0x7eb2dd"

[[colors.indexed_colors]]
index = 21
color = "0xfb94ff"
