# Base16 Vice Dark - alacritty color config
# Thomas Leon Highbaugh

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x181818'
foreground = '0x818181'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x181818'
cursor = '0x818181'

# Normal colors
[colors.normal]
black = '0x181818'
red = '0xff29a8'
green = '0x0badff'
yellow = '0xf0ffaa'
blue = '0x00eaff'
magenta = '0x00f6d9'
cyan = '0x8265ff'
white = '0x818181'

# Bright colors
[colors.bright]
black = '0x3f3f3f'
red = '0x85ffe0'
green = '0x222222'
yellow = '0x323232'
blue = '0x666666'
magenta = '0xc6c6c6'
cyan = '0xff3d81'
white = '0xe9e9e9'
