# Base16 Spaceduck 256 - alacritty color config
# Guillermo Rodriguez (pineapplegiant)

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0x686f9a'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0x686f9a'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xe33400'
green = '0x5ccc96'
yellow = '0xb3a1e6'
blue = '0x00a3cc'
magenta = '0xf2ce00'
cyan = '0x7a5ccc'
white = '0x686f9a'

# Bright colors
[colors.bright]
black = '0x686f9a'
red = '0xe33400'
green = '0x5ccc96'
yellow = '0xb3a1e6'
blue = '0x00a3cc'
magenta = '0xf2ce00'
cyan = '0x7a5ccc'
white = '0xf0f1ce'

[[colors.indexed_colors]]
index = 16
color = "0xe33400"

[[colors.indexed_colors]]
index = 17
color = "0x7a5ccc"

[[colors.indexed_colors]]
index = 18
color = "0x5ccc96"

[[colors.indexed_colors]]
index = 19
color = "0xb3a1e6"

[[colors.indexed_colors]]
index = 20
color = "0x00a3cc"

[[colors.indexed_colors]]
index = 21
color = "0xf2ce00"
