# Base16 Apprentice 256 - alacritty color config
# romainl

# Default colors
[colors.primary]
background = '0x262626'
foreground = '0x5F5F87'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x262626'
cursor = '0x5F5F87'

# Normal colors
[colors.normal]
black = '0x262626'
red = '0x444444'
green = '0xFFFFAF'
yellow = '0x87AF87'
blue = '0x8787AF'
magenta = '0x5FAFAF'
cyan = '0x87AFD7'
white = '0x5F5F87'

# Bright colors
[colors.bright]
black = '0x87875F'
red = '0x444444'
green = '0xFFFFAF'
yellow = '0x87AF87'
blue = '0x8787AF'
magenta = '0x5FAFAF'
cyan = '0x87AFD7'
white = '0x6C6C6C'

[[colors.indexed_colors]]
index = 16
color = "0xFF8700"

[[colors.indexed_colors]]
index = 17
color = "0xBCBCBC"

[[colors.indexed_colors]]
index = 18
color = "0xAF5F5F"

[[colors.indexed_colors]]
index = 19
color = "0x5F875F"

[[colors.indexed_colors]]
index = 20
color = "0x5F87AF"

[[colors.indexed_colors]]
index = 21
color = "0x5F8787"
