# Base16 Framer 256 - alacritty color config
# Framer (Maintained by Jesse Hoyos)

# Default colors
[colors.primary]
background = '0x181818'
foreground = '0xD0D0D0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x181818'
cursor = '0xD0D0D0'

# Normal colors
[colors.normal]
black = '0x181818'
red = '0xFD886B'
green = '0x32CCDC'
yellow = '0xFECB6E'
blue = '0x20BCFC'
magenta = '0xBA8CFC'
cyan = '0xACDDFD'
white = '0xD0D0D0'

# Bright colors
[colors.bright]
black = '0x747474'
red = '0xFD886B'
green = '0x32CCDC'
yellow = '0xFECB6E'
blue = '0x20BCFC'
magenta = '0xBA8CFC'
cyan = '0xACDDFD'
white = '0xEEEEEE'

[[colors.indexed_colors]]
index = 16
color = "0xFC4769"

[[colors.indexed_colors]]
index = 17
color = "0xB15F4A"

[[colors.indexed_colors]]
index = 18
color = "0x151515"

[[colors.indexed_colors]]
index = 19
color = "0x464646"

[[colors.indexed_colors]]
index = 20
color = "0xB9B9B9"

[[colors.indexed_colors]]
index = 21
color = "0xE8E8E8"
