# Base16 Horizon Dark 256 - alacritty color config
# MichaÃ«l Ball (http://github.com/michael-ball/)

# Default colors
[colors.primary]
background = '0x1C1E26'
foreground = '0xCBCED0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1C1E26'
cursor = '0xCBCED0'

# Normal colors
[colors.normal]
black = '0x1C1E26'
red = '0xE95678'
green = '0x29D398'
yellow = '0xFAC29A'
blue = '0x26BBD9'
magenta = '0xEE64AC'
cyan = '0x59E1E3'
white = '0xCBCED0'

# Bright colors
[colors.bright]
black = '0x6F6F70'
red = '0xE95678'
green = '0x29D398'
yellow = '0xFAC29A'
blue = '0x26BBD9'
magenta = '0xEE64AC'
cyan = '0x59E1E3'
white = '0xE3E6EE'

[[colors.indexed_colors]]
index = 16
color = "0xFAB795"

[[colors.indexed_colors]]
index = 17
color = "0xF09383"

[[colors.indexed_colors]]
index = 18
color = "0x232530"

[[colors.indexed_colors]]
index = 19
color = "0x2E303E"

[[colors.indexed_colors]]
index = 20
color = "0x9DA0A2"

[[colors.indexed_colors]]
index = 21
color = "0xDCDFE4"
