# Base16 DanQing 256 - alacritty color config
# Wenhan Zhu (Cosmos) (zhuwenhan950913@gmail.com)

# Default colors
[colors.primary]
background = '0x2d302f'
foreground = '0xe0f0eF'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2d302f'
cursor = '0xe0f0eF'

# Normal colors
[colors.normal]
black = '0x2d302f'
red = '0xF9906F'
green = '0x8AB361'
yellow = '0xF0C239'
blue = '0xB0A4E3'
magenta = '0xCCA4E3'
cyan = '0x30DFF3'
white = '0xe0f0eF'

# Bright colors
[colors.bright]
black = '0x9da8a3'
red = '0xF9906F'
green = '0x8AB361'
yellow = '0xF0C239'
blue = '0xB0A4E3'
magenta = '0xCCA4E3'
cyan = '0x30DFF3'
white = '0xfcfefd'

[[colors.indexed_colors]]
index = 16
color = "0xB38A61"

[[colors.indexed_colors]]
index = 17
color = "0xCA6924"

[[colors.indexed_colors]]
index = 18
color = "0x434846"

[[colors.indexed_colors]]
index = 19
color = "0x5a605d"

[[colors.indexed_colors]]
index = 20
color = "0xcad8d2"

[[colors.indexed_colors]]
index = 21
color = "0xecf6f2"
